# Generated by Django 3.2.10 on 2022-04-04 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topicranking',
            options={'ordering': ['-votes']},
        ),
    ]
