# Generated by Django 4.0.3 on 2022-04-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='num_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='num_comments',
            field=models.IntegerField(default=0),
        ),
    ]
