# Generated by Django 4.0.3 on 2022-03-31 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_post_feed_id_rename_post_story_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='id',
            new_name='Feed',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='id',
            new_name='Story',
        ),
    ]
