# Generated by Django 4.0.3 on 2022-04-15 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_feed_num_comments_story_num_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ['create_time']},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['create_time']},
        ),
    ]
