# Generated by Django 4.0.3 on 2022-04-15 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_feed_options_alter_story_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ['-create_time']},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-create_time']},
        ),
    ]
