# Generated by Django 4.0.3 on 2022-03-31 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_feed_feed_post_rename_story_story_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='post',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='post',
            new_name='id',
        ),
    ]
