# Generated by Django 3.2.10 on 2022-04-02 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_post_feed_id_rename_post_story_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='UserInfo_id', serialize=False, to='api.userlogin'),
        ),
    ]
