# Generated by Django 4.0.3 on 2022-04-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_feed_anonymous_alter_feed_emoji_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='anonymous',
            field=models.BooleanField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='feed',
            name='emoji',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='feed',
            name='view_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='feed',
            name='visibility',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='story',
            name='anonymous',
            field=models.BooleanField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='story',
            name='view_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='story',
            name='visibility',
            field=models.CharField(blank=True, max_length=36),
        ),
    ]
