# Generated by Django 4.0.3 on 2022-04-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_feed_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='parentIsStory',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='feed',
            name='num_comments',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='feed',
            name='num_likes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='feed',
            name='num_shares',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='story',
            name='num_comments',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='story',
            name='num_likes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='story',
            name='num_shares',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
