# Generated by Django 4.0.3 on 2022-04-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_feed_topic_alter_feed_user_alter_story_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='parentIsStory',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
