# Generated by Django 3.2.8 on 2022-04-24 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_feed_parentisstory'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='parentFeed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parentFeedF', to='api.feed'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='parentStory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parentStoryF', to='api.story'),
        ),
        migrations.AlterField(
            model_name='story',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parentStoryS', to='api.story'),
        ),
    ]
