# Generated by Django 3.2.8 on 2022-04-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220424_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='DateHappened',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
