# Generated by Django 3.2.8 on 2022-04-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_story_datehappened'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='Exist',
            field=models.CharField(choices=[('1', 'EXIST'), ('0', 'EXISTED')], default='1', max_length=7),
        ),
    ]
