# Generated by Django 3.2.8 on 2022-04-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_story_exist'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='username',
            field=models.CharField(blank=True, default='匿名', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='username',
            field=models.CharField(blank=True, default='匿名', max_length=150, null=True),
        ),
    ]
