# Generated by Django 3.2.8 on 2022-04-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20220424_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='Exist',
            field=models.CharField(choices=[('EXIST', 'EXIST'), ('EXISTED', 'EXISTED')], default='EXIST', max_length=7),
        ),
    ]
