# Generated by Django 3.2.8 on 2022-04-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_story_exist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='DateHappened',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
