# Generated by Django 3.2.8 on 2022-04-27 22:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20220424_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='hearts',
            field=models.ManyToManyField(related_name='hearts', to=settings.AUTH_USER_MODEL),
        ),
    ]
