# Generated by Django 3.2.8 on 2022-04-28 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_story_hearts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='hearts',
        ),
        migrations.CreateModel(
            name='likeStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storyLiked', to='api.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userLiking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
