# Generated by Django 3.2.8 on 2022-05-12 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20220430_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='storycomment',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='storycomment',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='storycomment',
            name='popup_note',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
