# Generated by Django 3.2.8 on 2022-05-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20220512_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='gender',
            field=models.BooleanField(default=True),
        ),
    ]
