# Generated by Django 3.2.8 on 2022-05-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_userlogin_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='social_media',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
