# Generated by Django 3.2.8 on 2022-05-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='button_prompt',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
