# Generated by Django 3.2.8 on 2022-06-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_topic_button_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='member_action',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
