# Generated by Django 3.2.8 on 2022-06-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_topic_member_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='requires_address',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
