# Generated by Django 3.2.8 on 2022-06-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20220601_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
