# Generated by Django 3.2.8 on 2022-06-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_userlogin_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='placeholder_txt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
