# Generated by Django 3.2.8 on 2022-06-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_story_placeholder_txt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='placeholder_txt',
        ),
        migrations.AddField(
            model_name='topic',
            name='placeholder_txt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
